# docker compose to startup a local ES cluster - pull-dog version (https://github.com/apps/pull-dog)
version: '3.6'
services:
  elasticsearch_searchguard_1:
    build:
      context: .
    image: xtermi2/elasticsearch-searchguard:pulldog
    container_name: elasticsearch_searchguard_1
    environment:
      node.name: "elasticsearch_searchguard_1"
      discovery.seed_hosts: elasticsearch_searchguard_2
      cluster.initial_master_nodes: "elasticsearch_searchguard_1, elasticsearch_searchguard_2"
      ES_JAVA_OPTS: "-Xms128m -Xmx128m"
      ROOT_CA: "root-ca.pem"
      ADMIN_PEM: "admin.pem"
      ADMIN_KEY: "admin.key"
      ADMIN_KEY_PASS: "default-secret"
      ELASTIC_PWD: "elastic"
      KIBANA_PWD: "kibana"
      BEATS_PWD: "beats"
    volumes:
      - ./src/test/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./src/test/test-certs:/usr/share/elasticsearch/config/certificates
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -X GET -f -k -u 'elastic:elastic' https://localhost:9200 || exit 1
      interval: 30s
      timeout: 5s
      retries: 10
    networks:
      - pulldognet
  elasticsearch_searchguard_2:
    image: xtermi2/elasticsearch-searchguard:pulldog
    container_name: elasticsearch_searchguard_2
    environment:
      node.name: "elasticsearch_searchguard_2"
      discovery.seed_hosts: elasticsearch_searchguard_1
      cluster.initial_master_nodes: "elasticsearch_searchguard_1, elasticsearch_searchguard_2"
      ES_JAVA_OPTS: "-Xms128m -Xmx128m"
      ROOT_CA: "root-ca.pem"
      ADMIN_PEM: "admin.pem"
      ADMIN_KEY: "admin.key"
      ADMIN_KEY_PASS: "default-secret"
      ELASTIC_PWD: "elastic"
      KIBANA_PWD: "kibana"
      BEATS_PWD: "beats"
    volumes:
      - ./src/test/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./src/test/test-certs:/usr/share/elasticsearch/config/certificates
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9200"
    healthcheck:
      test: curl -X GET -f -k -u 'elastic:elastic' https://localhost:9200 || exit 1
      interval: 30s
      timeout: 5s
      retries: 10
    networks:
      - pulldognet
  kibana:
    image: xtermi2/kibana-searchguard:7.9.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: "https://elasticsearch_searchguard_1:9200"
      ELASTICSEARCH_SSL_VERIFICATIONMODE: "none"
      ELASTICSEARCH_USERNAME: "kibana"
      ELASTICSEARCH_PASSWORD: "kibana"
    ports:
      - "5601:5601"
    depends_on:
      - "elasticsearch_searchguard_1"
      - "elasticsearch_searchguard_2"
    healthcheck:
      test: curl -X GET -f http://localhost:5601/status || exit 1
      interval: 30s
      timeout: 5s
      retries: 10
    networks:
      - pulldognet
  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.9.1
    container_name: filebeat
    # to overwrite the -e that disables logging to file and disable strict permission checks for filebeat.yml!
    command: -c filebeat.yml -strict.perms=false
    volumes:
      - ./src/test/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    ports:
      - "5066:5066"
    healthcheck:
      test: curl -X GET -f http://localhost:5066 || exit 1
      interval: 30s
      timeout: 5s
      retries: 10
    depends_on:
      - elasticsearch_searchguard_1
      - elasticsearch_searchguard_2
    networks:
      - pulldognet
networks:
  pulldognet: